//твой возраст;
let age = 22;
//год рождения;
let yourBirthYear = 2020;
//число рождения (без нолика в начале);
let yourBirthday = 17;
//количество родных братьев;
let numbersOfBrothers = 1;
//количество родных сестер;
let numbersOfSisters = 2;
//количество человек в семье;
let numbersOfPeopleInTheFamily = 6;
//стоимость проезда до места обучения;
let fare = 100;
//текущий год;
let thisYear = 2022;
//курс доллара;
let dollarsCount = 61.82;
//курс евро;
let euroCount = 61.23;
//курс биткоина;
let bitcoinCountInDollars = 20542.2;
//курс биткоина в рублях
let bitcoinCountInRubles = 20542.2 * dollarsCount;

//текущий год минус год рождения;
let lastYear = thisYear - 1;
//текущий год минус твой возраст;
let countMyBirthYear = thisYear - age;
//количество родных братьев плюс количество родных сестер;
let numbersOfBrothersAndSisters = numbersOfSisters * numbersOfBrothers;
//курс евро умноженный на 1000;
let count1000euro = euroCount * 1000;
//курс доллара умноженный на 2.5;
let count2AndHalfDollars = 2.5 * dollarsCount; 
//курс биткоина разделенный на 10000;
let bitcoinCountInScale = bitcoinCountInDollars / 10000;
//стоимость проезда до места обучения разделенная на курс доллара;
let fareInDollars = fare / dollarsCount;
//количество человек в семье минус количество братьев минус количество сестер;
let FamilyWithoutSister = numbersOfPeopleInTheFamily - numbersOfSisters;
//0 деленный на твой возраст;
let defoultAges = 0 / age;
//35 минус твой возраст;
let ageDifference = 35 - age;